export const suggestions = [
  "Write a creative story about time travel",
  "Explain quantum physics in simple terms",
  "Create a recipe for a healthy breakfast",
  "Help me plan a weekend trip to the mountains",
  "Generate ideas for a small business",
  "Write a creative story about time travel",
  "Explain quantum physics in simple terms",
  "Create a recipe for a healthy breakfast",
  "Help me plan a weekend trip to the mountains",
  "Generate ideas for a small business",
  "Write a creative story about time travel",
  "Explain quantum physics in simple terms",
  "Create a recipe for a healthy breakfast",
  "Help me plan a weekend trip to the mountains",
  "Generate ideas for a small business",
  "Write a creative story about time travel",
  "Explain quantum physics in simple terms",
  "Create a recipe for a healthy breakfast",
  "Help me plan a weekend trip to the mountains",
  "Generate ideas for a small business",
  "Write a creative story about time travel",
  "Explain quantum physics in simple terms",
  "Create a recipe for a healthy breakfast",
  "Help me plan a weekend trip to the mountains",
  "Generate ideas for a small business",
];
