CREATE VIEW "PatientInfo" AS
SELECT
  patient_id AS id,
  first_name AS "firstName",
  last_name AS "lastName",
  date_of_birth AS "dateOfBirth",
  gender,
  patient_phone AS phone,
  patient_email AS email,
  parent_guardian_name AS "parentGuardianName",
  parent_guardian_phone AS "parentGuardianPhone",
  parent_guardian_email AS "parentGuardianEmail",
  relation_to_patient AS "relationToPatient",
  address,
  emergency_contact_name AS "emergencyContactName",
  emergency_contact_number AS "emergencyContactNumber",
  relation_to_emergency AS "relationToEmergency",
  blood_group AS "bloodGroup",
  allergies,
  medical_conditions AS "medicalConditions",
  medical_history AS "medicalHistory",
  insurance_provider AS "insuranceProvider",
  insurance_number AS "insuranceNumber",
  privacy_consent AS "privacyConsent",
  service_consent AS "serviceConsent",
  medical_consent AS "medicalConsent",
  img,
  color_code AS "colorCode",
  created_at AS "createdAt",
  updated_at AS "updatedAt"
FROM patients;